INSERT INTO Admins(username,password) 
VALUES('Haris','root');

SELECT * FROM ADMINS

SELECT * FROM USERS

SELECT * FROM Expenses

DELETE FROM ADMINS WHERE username='Haris';

ALTER TABLE EXPENSES
DROP CONSTRAINT FK__EXPENSES__user_i__3D5E1FD2;

ALTER TABLE EXPENSES
ADD CONSTRAINT FK_Expenses_UserId FOREIGN KEY (user_id)
REFERENCES Users(user_id)
ON DELETE CASCADE;
